-- =====================================================================
-- SEO Workbench Migration 002: Rule Engine v2
-- Author  : generated from docs/rule-extraction.md §5
-- Depends : 001_agent_memory_schema.sql
--           (requires seo_agent.set_updated_at() and pgcrypto extension)
-- Target  : PostgreSQL 14+
-- Idempotent: yes (all DDL uses IF NOT EXISTS / OR REPLACE)
--
-- What this migration adds
-- -------------------------
-- Three new tables in the seo_agent schema:
--   1. rule_sets        - versioned container of the seo-standard.json payload
--   2. rule_field_map  - reverse index "rule key in JSON -> hardcoded code location"
--   3. rule_audit_log  - append-only lifecycle log for every rule-set change
--
-- Plus two business views, two updated_at triggers, and one type-check trigger.
--
-- PK strategy (see docs/rule-extraction.md §5.0):
--   v1 tables keep uuid PKs (cross-process, Node.js <-> Python).
--   v2 tables use bigint GENERATED ALWAYS AS IDENTITY (internal-only).
--   External references always use natural keys (name+version, layer+key).
-- =====================================================================

SET search_path = seo_agent;

-- ---------------------------------------------------------------------
-- 1) rule_sets
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS seo_agent.rule_sets (
  id                bigint      GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name              varchar(64) NOT NULL,
  version           varchar(32) NOT NULL,
  source            varchar(16) NOT NULL,
  payload           jsonb       NOT NULL,
  is_active         boolean     NOT NULL DEFAULT false,
  effective_at      timestamptz NOT NULL DEFAULT now(),
  created_by        varchar(64),
  notes             text,
  parent_version_id bigint      REFERENCES seo_agent.rule_sets(id) ON DELETE SET NULL,
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT rule_sets_source_chk
    CHECK (source IN ('file','db','api')),
  CONSTRAINT rule_sets_version_chk
    CHECK (version ~ '^[0-9]+\.[0-9]+\.[0-9]+([-.+][0-9A-Za-z.-]+)?$'),
  CONSTRAINT rule_sets_payload_object_chk
    CHECK (jsonb_typeof(payload) = 'object'),
  CONSTRAINT rule_sets_id_positive_chk
    CHECK (id > 0)
);

COMMENT ON TABLE  seo_agent.rule_sets IS
  'Versioned container of the entire seo-standard.json payload. Active version is selected by partial unique index rule_sets_one_active_per_name. Business key is (name, version); surrogate bigint PK is internal-only.';
COMMENT ON COLUMN seo_agent.rule_sets.id                IS 'Surrogate bigint PK, generated by IDENTITY. Internal-only; external references use (name, version).';
COMMENT ON COLUMN seo_agent.rule_sets.name              IS 'Rule family name, e.g. seo-standard.';
COMMENT ON COLUMN seo_agent.rule_sets.version           IS 'SemVer (or YYYY-MM-DD) string; unique within (name, version).';
COMMENT ON COLUMN seo_agent.rule_sets.source            IS 'Origin of this version: file (JSON import), db (UI edit), api (programmatic).';
COMMENT ON COLUMN seo_agent.rule_sets.payload           IS 'JSON object structurally compatible with workflows/seo-standard.json.';
COMMENT ON COLUMN seo_agent.rule_sets.is_active         IS 'At most one row per name may be true (enforced by partial unique index rule_sets_one_active_per_name).';
COMMENT ON COLUMN seo_agent.rule_sets.effective_at      IS 'When this version became / will become the live one.';
COMMENT ON COLUMN seo_agent.rule_sets.created_by        IS 'Operator id or stage name that produced this version.';
COMMENT ON COLUMN seo_agent.rule_sets.notes             IS 'Free-text change description for audit.';
COMMENT ON COLUMN seo_agent.rule_sets.parent_version_id IS 'Optional lineage pointer: forked from this version.';
COMMENT ON COLUMN seo_agent.rule_sets.created_at        IS 'Row creation timestamp.';
COMMENT ON COLUMN seo_agent.rule_sets.updated_at        IS 'Last modification timestamp (trigger-maintained).';

-- At most one active version per rule family.
CREATE UNIQUE INDEX IF NOT EXISTS rule_sets_one_active_per_name
  ON seo_agent.rule_sets (name)
  WHERE is_active;

-- (name, version) uniqueness.
CREATE UNIQUE INDEX IF NOT EXISTS rule_sets_name_version_uk
  ON seo_agent.rule_sets (name, version);

-- Hot path: "find currently active ruleset for family X".
CREATE INDEX IF NOT EXISTS rule_sets_family_active_idx
  ON seo_agent.rule_sets (name, effective_at DESC);

-- JSONB GIN for queries like "which versions set demandCoeff?".
CREATE INDEX IF NOT EXISTS rule_sets_payload_gin_idx
  ON seo_agent.rule_sets USING gin (payload jsonb_path_ops);

DROP TRIGGER IF EXISTS set_rule_sets_updated_at ON seo_agent.rule_sets;
CREATE TRIGGER set_rule_sets_updated_at
BEFORE UPDATE ON seo_agent.rule_sets
FOR EACH ROW EXECUTE FUNCTION seo_agent.set_updated_at();

-- ---------------------------------------------------------------------
-- 2) rule_field_map
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS seo_agent.rule_field_map (
  id            bigint      GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  rule_set_id   bigint      NOT NULL REFERENCES seo_agent.rule_sets(id) ON DELETE CASCADE,
  rule_layer    varchar(32) NOT NULL,
  rule_key      varchar(128) NOT NULL,
  display_name  varchar(128) NOT NULL,
  value_type    varchar(16) NOT NULL,
  default_value jsonb,
  source_file   varchar(256) NOT NULL,
  source_line   integer,
  is_migrated   boolean     NOT NULL DEFAULT false,
  notes         text,
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT rule_field_map_layer_chk
    CHECK (rule_layer IN ('classifier','scorer','content_plan','assets','locale',
                          'workflow','output_format','references','anchor','images','global_plan')),
  CONSTRAINT rule_field_map_type_chk
    CHECK (value_type IN ('number','string','boolean','array','object')),
  CONSTRAINT rule_field_map_key_chk
    CHECK (rule_key = lower(rule_key) AND rule_key ~ '^[a-z0-9_.]+$'),
  CONSTRAINT rule_field_map_line_chk
    CHECK (source_line IS NULL OR source_line > 0),
  CONSTRAINT rule_field_map_id_positive_chk
    CHECK (id > 0)
);

COMMENT ON TABLE  seo_agent.rule_field_map IS
  'Reverse index: which JSON rule key corresponds to which hardcoded location in code. Populated during the hardcode->config migration; consumed by UI rule editor and audit tools.';
COMMENT ON COLUMN seo_agent.rule_field_map.id            IS 'Surrogate bigint PK, generated by IDENTITY. Internal-only; business lookup uses (rule_set_id, rule_layer, rule_key).';
COMMENT ON COLUMN seo_agent.rule_field_map.rule_set_id   IS 'FK -> rule_sets.id. ON DELETE CASCADE so that dropping a rule-set version removes its field map.';
COMMENT ON COLUMN seo_agent.rule_field_map.rule_layer    IS 'Logical layer the key belongs to.';
COMMENT ON COLUMN seo_agent.rule_field_map.rule_key      IS 'Dot-path inside payload. Lowercase, snake_case segments separated by ".".';
COMMENT ON COLUMN seo_agent.rule_field_map.display_name  IS 'Human-readable name for UI.';
COMMENT ON COLUMN seo_agent.rule_field_map.value_type    IS 'Declared JSON value type; checked against default_value at write time.';
COMMENT ON COLUMN seo_agent.rule_field_map.default_value IS 'Fallback if payload omits this key.';
COMMENT ON COLUMN seo_agent.rule_field_map.source_file   IS 'Original code location (file path relative to repo root).';
COMMENT ON COLUMN seo_agent.rule_field_map.source_line   IS 'Original code location (1-based line).';
COMMENT ON COLUMN seo_agent.rule_field_map.is_migrated   IS 'true once the corresponding hardcode has been removed and reads from payload instead.';
COMMENT ON COLUMN seo_agent.rule_field_map.notes         IS 'Migration notes, e.g. which release removed the hardcode.';
COMMENT ON COLUMN seo_agent.rule_field_map.created_at    IS 'Row creation timestamp.';
COMMENT ON COLUMN seo_agent.rule_field_map.updated_at    IS 'Last modification timestamp (trigger-maintained).';

-- Business uniqueness: a given (layer, key) can only be mapped once per rule_set version.
CREATE UNIQUE INDEX IF NOT EXISTS rule_field_map_set_layer_key_uk
  ON seo_agent.rule_field_map (rule_set_id, rule_layer, rule_key);

-- Audit "what hardcodes still remain in code?" -> WHERE NOT is_migrated.
CREATE INDEX IF NOT EXISTS rule_field_map_unmigrated_idx
  ON seo_agent.rule_field_map (rule_layer, is_migrated);

-- Lookup "which version owned this rule_key?".
CREATE INDEX IF NOT EXISTS rule_field_map_key_idx
  ON seo_agent.rule_field_map (rule_layer, rule_key);

-- JSONB GIN for queries like "which keys have default_value of type number > 10?".
CREATE INDEX IF NOT EXISTS rule_field_map_default_gin_idx
  ON seo_agent.rule_field_map USING gin (default_value jsonb_path_ops);

DROP TRIGGER IF EXISTS set_rule_field_map_updated_at ON seo_agent.rule_field_map;
CREATE TRIGGER set_rule_field_map_updated_at
BEFORE UPDATE ON seo_agent.rule_field_map
FOR EACH ROW EXECUTE FUNCTION seo_agent.set_updated_at();

-- Enforce that rule_field_map.default_value's JSON type matches declared value_type.
CREATE OR REPLACE FUNCTION seo_agent.check_default_value_type()
RETURNS trigger AS $$
DECLARE
  got text;
BEGIN
  IF NEW.default_value IS NULL THEN
    RETURN NEW;
  END IF;
  got := jsonb_typeof(NEW.default_value);
  IF (NEW.value_type = 'number'  AND got <> 'number')
  OR (NEW.value_type = 'string'  AND got <> 'string')
  OR (NEW.value_type = 'boolean' AND got <> 'boolean')
  OR (NEW.value_type = 'array'   AND got <> 'array')
  OR (NEW.value_type = 'object'  AND got <> 'object') THEN
    RAISE EXCEPTION 'rule_field_map.default_value jsonb type (%) does not match value_type (%)',
                    got, NEW.value_type;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS rule_field_map_default_type_trg ON seo_agent.rule_field_map;
CREATE TRIGGER rule_field_map_default_type_trg
BEFORE INSERT OR UPDATE OF default_value, value_type ON seo_agent.rule_field_map
FOR EACH ROW EXECUTE FUNCTION seo_agent.check_default_value_type();

-- ---------------------------------------------------------------------
-- 3) rule_audit_log
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS seo_agent.rule_audit_log (
  id            bigint      GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  rule_set_id   bigint      NOT NULL REFERENCES seo_agent.rule_sets(id) ON DELETE RESTRICT,
  action        varchar(16) NOT NULL,
  actor         varchar(64) NOT NULL,
  reason        text,
  snapshot_diff jsonb       NOT NULL DEFAULT '{}'::jsonb,
  created_at    timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT rule_audit_action_chk
    CHECK (action IN ('activate','deactivate','create','rollback','supersede')),
  CONSTRAINT rule_audit_id_positive_chk
    CHECK (id > 0)
);

COMMENT ON TABLE  seo_agent.rule_audit_log IS
  'Append-only audit log of every rule-set lifecycle event. Never UPDATE; INSERT only.';
COMMENT ON COLUMN seo_agent.rule_audit_log.id            IS 'Surrogate bigint PK, generated by IDENTITY. Append-only; never UPDATE.';
COMMENT ON COLUMN seo_agent.rule_audit_log.rule_set_id   IS 'FK -> rule_sets.id. ON DELETE RESTRICT preserves auditability when a version is removed.';
COMMENT ON COLUMN seo_agent.rule_audit_log.action        IS 'Lifecycle verb: activate | deactivate | create | rollback | supersede.';
COMMENT ON COLUMN seo_agent.rule_audit_log.actor         IS 'Operator id or automation stage name.';
COMMENT ON COLUMN seo_agent.rule_audit_log.reason        IS 'Free-text justification.';
COMMENT ON COLUMN seo_agent.rule_audit_log.snapshot_diff IS 'Computed diff vs. previous version (or vs. baseline on first create).';
COMMENT ON COLUMN seo_agent.rule_audit_log.created_at    IS 'Event timestamp.';

CREATE INDEX IF NOT EXISTS rule_audit_set_idx
  ON seo_agent.rule_audit_log (rule_set_id, created_at DESC);

-- ---------------------------------------------------------------------
-- 4) Business views
-- ---------------------------------------------------------------------
CREATE OR REPLACE VIEW seo_agent.v_active_rule_set AS
SELECT *
FROM   seo_agent.rule_sets
WHERE  is_active = true
  AND  effective_at <= now();

COMMENT ON VIEW seo_agent.v_active_rule_set IS
  'Currently effective active rule-set per family. The hot path for engine layer reads.';

CREATE OR REPLACE VIEW seo_agent.v_active_rule_field_map AS
SELECT m.*
FROM   seo_agent.rule_field_map m
JOIN   seo_agent.v_active_rule_set s ON s.id = m.rule_set_id;

COMMENT ON VIEW seo_agent.v_active_rule_field_map IS
  'Field-map rows belonging to the currently active rule-set. Drives UI rule editor.';

-- ---------------------------------------------------------------------
-- 5) Sequence continuation safety net
--    Run after a bulk restore: SELECT setval(seq, max(id)) for each.
--    Documented here so operators know the convention; not executed.
-- ---------------------------------------------------------------------
-- SELECT setval(pg_get_serial_sequence('seo_agent.rule_sets',       'id'),
--               COALESCE((SELECT max(id) FROM seo_agent.rule_sets),       0));
-- SELECT setval(pg_get_serial_sequence('seo_agent.rule_field_map', 'id'),
--               COALESCE((SELECT max(id) FROM seo_agent.rule_field_map), 0));
-- SELECT setval(pg_get_serial_sequence('seo_agent.rule_audit_log', 'id'),
--               COALESCE((SELECT max(id) FROM seo_agent.rule_audit_log), 0));